# Generated by Django 5.0 on 2023-12-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_groupdb_dtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdb',
            name='Dtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
